# Generated by Django 4.1.3 on 2024-04-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='lecturer_id',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='office',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='phone_number',
        ),
    ]
