# Generated by Django 4.1.3 on 2024-04-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='image',
        ),
    ]
