# Generated by Django 4.1.3 on 2024-04-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_lecturer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(),
        ),
    ]
