# Generated by Django 4.1.3 on 2024-04-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_lecturer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='bio',
            field=models.TextField(default='This is me'),
        ),
    ]
