# Generated by Django 4.1.3 on 2024-05-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lecturer_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='note',
            name='week',
            field=models.CharField(blank=True, default='Week 1', max_length=100, null=True),
        ),
    ]
