# Generated by Django 5.0.2 on 2024-10-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='course',
        ),
    ]
