# Generated by Django 5.0.2 on 2024-10-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_note_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='week',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
